version: '3.8'
services:
  spookyspot-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: spookyspot-frontend
    restart: unless-stopped
    networks:
      - shared_portainer_network # Changed this
    depends_on:
      - spookyspot-backend

  spookyspot-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spookyspot-backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=spookyspot
      - DB_HOST=spookyspot-db
      - SCHEMA=${SCHEMA}
    networks:
      - shared_portainer_network # Changed this
    depends_on:
      - spookyspot-db
    restart: unless-stopped

  spookyspot-db:
    image: postgres:15-alpine
    container_name: spookyspot-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=spookyspot
    volumes:
      - spookyspot_data:/var/lib/postgresql/data
    networks:
      - shared_portainer_network # Changed this
    restart: unless-stopped

networks:
  shared_portainer_network:
    external: true # Use existing network

volumes:
  spookyspot_data:
