version: '3.8'
services:
  spookyspot-frontend:
    build:
      context: /home/steven/projects/aa-projects/spookyspot/frontend
    container_name: spookyspot-frontend
    networks:
      - shared_portainer_network
    restart: unless-stopped

  spookyspot-backend:
    build:
      context: /home/steven/projects/aa-projects/spookyspot/backend
    container_name: spookyspot-backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=spookyspot
      - DB_HOST=spookyspot-db
      - SCHEMA=${SCHEMA}
    networks:
      - shared_portainer_network
    restart: unless-stopped

  spookyspot-db:
    image: postgres:15-alpine
    container_name: spookyspot-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=spookyspot
    volumes:
      - spookyspot_data:/var/lib/postgresql/data
    networks:
      - shared_portainer_network
    restart: unless-stopped

networks:
  shared_portainer_network:
    external: true

volumes:
  spookyspot_data:
