version: '3.8'

services:
  spookyspot-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BUILDKIT_STEP_LOG_MAX_SIZE=10485760
    container_name: spookyspot-frontend
    expose:
      - 80
    networks:
      - shared_portainer_network
    depends_on:
      - spookyspot-backend
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        mode: 'non-blocking'
        max-buffer-size: '4m'
    environment:
      - NODE_DEBUG=*

  spookyspot-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - BUILDKIT_STEP_LOG_MAX_SIZE=10485760
    container_name: spookyspot-backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=spookyspot
      - DB_HOST=spookyspot-db
      - SCHEMA=airBnbSchema
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - DEBUG=express:*,app:*,sequelize:*
      - NODE_DEBUG=*
      - SEQUELIZE_LOGGING=true
    networks:
      - shared_portainer_network
    depends_on:
      - spookyspot-db
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        mode: 'non-blocking'
        max-buffer-size: '4m'

  spookyspot-db:
    image: postgres:15-alpine
    container_name: spookyspot-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=spookyspot
      - SCHEMA=airBnbSchema
      - POSTGRES_INITDB_ARGS="--debug --verbose"
      - POSTGRES_LOGGING=true
    volumes:
      - spookyspot_data:/var/lib/postgresql/data
    networks:
      - shared_portainer_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d spookyspot']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        mode: 'non-blocking'
        max-buffer-size: '4m'

networks:
  shared_portainer_network:
    external: true

volumes:
  spookyspot_data:
