version: '3.8'

services:
  spookyspot-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: spookyspot-frontend
    networks:
      - shared_portainer_network
    depends_on:
      - spookyspot-backend
    restart: unless-stopped

  spookyspot-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spookyspot-backend
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-5000}
      DB_USER: ${DB_USER:?DB_USER is required}
      DB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is required}
      DB_NAME: ${DB_NAME:-spookyspot}
      DB_HOST: ${DB_HOST:-spookyspot-db}
      SCHEMA: ${SCHEMA:?SCHEMA is required}
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET is required}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-604800}
    networks:
      - shared_portainer_network
    depends_on:
      - spookyspot-db
    restart: unless-stopped

  spookyspot-db:
    image: postgres:15-alpine
    container_name: spookyspot-db
    environment:
      POSTGRES_USER: ${DB_USER:?DB_USER is required}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is required}
      POSTGRES_DB: ${DB_NAME:-spookyspot}
    volumes:
      - spookyspot_data:/var/lib/postgresql/data
    networks:
      - shared_portainer_network
    restart: unless-stopped

networks:
  shared_portainer_network:
    external: true

volumes:
  spookyspot_data:
